version: '3.5'
services:
  socks5:
    image: jc5lziy3hvfv5ux/socks5-alpine3.19
    restart: always
    environment:
      SOCKS5_USER: ${SOCKS5_USER}
      SOCKS5_PASSWORD: ${SOCKS5_PASSWORD}
      WITE_LIST_IPS: ${WITE_LIST_IPS} # example: 192.168.1.243,185.52.141.19
    volumes:
      - "./runtime/logs/socks5:/var/log:cached"
    ports:
      - ${SOCKS5_PORT:-1080}:1080
